apiVersion : apps/v1
kind: Deployment
metadata:
  name: "cvaksclusterfx-1eef"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "cvaksclusterfx-1eef"
  template:
    metadata:
      labels:
        app: "cvaksclusterfx-1eef"
    spec:
      containers:
        - name: "cvaksclusterfx-1eef"
          image: "cvacrfx.azurecr.io/cvaksclusterfx"
          ports:
          - containerPort: 8080