on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: cvacrfx.azurecr.io
        username: ${{ secrets.acr_cvacrfx_username }}
        password: ${{ secrets.acr_cvacrfx_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/agent" -f  "https://github.com/optimizely/agent/blob/master/scripts/dockerfiles/Dockerfile.static" -t cvacrfx.azurecr.io/cvaksclusterfx:${{ github.sha }} --label dockerfile-path=https://github.com/optimizely/agent/blob/master/scripts/dockerfiles/Dockerfile.static
        docker push cvacrfx.azurecr.io/cvaksclusterfx:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cvaksclusterfx_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cvaksclusterfx93d4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cvaksclusterfx93d4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cvaksclusterfx93d4
        container-registry-url: cvacrfx.azurecr.io
        container-registry-username: ${{ secrets.acr_cvacrfx_username }}
        container-registry-password: ${{ secrets.acr_cvacrfx_password }}
        secret-name: cvaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: cvaksclusterfx93d4
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          cvacrfx.azurecr.io/cvaksclusterfx:${{ github.sha }}
        imagepullsecrets: |
          cvaksclusterdockerauth
